### ISSUE TITLE
About the hyperparameters on ImageNet32 dataset of MaskCon

### ISSUE THREAD

**Issue by ReynardLin** [MrChenFeng/MaskCon_CVPR2023#2]
Recently I am reproducing your work MaskCon and it is a very intresting work. But I have confuse about the hyperparameters on ImageNet32 dataset of MaskCon. And your job contains hyperparameters for all other datasets except Imagenet32. Would you please offer the best hyperparameters for ImageNet32 of all methods including MaskCon, Grafit and CoIns?

**Comment by MrChenFeng** [comment]
Hi,
It is initially included in the supplementary file but was unintentionally omitted in the final camera-ready version. Please refer to below setting:
![c40995dce60746b54bc1cd4e6aada18](https://github.com/MrChenFeng/MaskCon_CVPR2023/assets/24207392/3a509e46-7d68-4f80-9c96-a8fd37fb710a)
